### ISSUE TITLE
Name resolution unit tests do not pass consistently

### ISSUE THREAD

**Issue by dobsonj** [IBM/vpc-node-label-updater#3]
There are 6 unit test cases in node_label_test.go and utils_test.go that match on a specific name resolution failure:
```
Temporary failure in name resolution
```

The problem with this is the name resolution error messages are a little different on each platform. When running `make test` on my Fedora dev machine, I get:
```
    node_label_test.go:82: Expected error : Get "https://invalid?name=": dial tcp: lookup invalid: Temporary failure in name resolution, got: Get "https://invalid?name=": dial tcp: lookup invalid: no such host. err : Get "https://invalid?name=": dial tcp: lookup invalid: no such host
```

And in OpenShift CI:
```
    node_label_test.go:82: Expected error : Get "https://invalid?name=": dial tcp: lookup invalid: Temporary failure in name resolution, got: Get "https://invalid?name=": dial tcp: lookup invalid on 172.30.0.10:53: no such host. err : Get "https://invalid?name=": dial tcp: lookup invalid on 172.30.0.10:53: no such host
```

To ensure the unit tests can run successfully in most environments, I'd recommend either removing those unit tests that match on the name resolution error, or implement some regex matching that is generic enough to work on most platforms.

**Comment by dobsonj** [comment]
cc @arahamad @meghnasiingh

**Comment by meghnasiingh** [comment]
@dobsonj https://github.com/IBM/vpc-node-label-updater/pull/4 fixes UT. Plz check

**Comment by dobsonj** [comment]
@meghnasiingh Thanks a lot, that works for me. Closing this issue.
